spring:
    datasource:
        url: jdbc:sqlite:db.sqlite
        driver-class-name: org.sqlite.JDBC
    jpa:
        hibernate:
            ddl-auto: none
        show-sql: false
        database-platform: org.hibernate.community.dialect.SQLiteDialect
        defer-datasource-initialization: true
    sql:
        init:
          mode: never
  # 파일 얿로드 크기 제한
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 10MB